### ISSUE TITLE
Doesn't appear to work with multisite

### ISSUE THREAD

**Issue by jeffpaul** [keesiemeijer/wp-local-version#1]
I've tried to use this script to create old versions of WordPress multisite to use for testing/triaging issues.  I've created a WP 5.0 multisite in Local, then ran through the script steps (noting there doesn't appear to be anywhere in the wp-local-version.sh script to denote multisite or not), and then when restarting the site it's no longer a multisite.  Is there something specific to do to ensure pre-existing multisite's stay as a multisite after this script runs?

**Comment by keesiemeijer** [comment]
Hi  jeffpaul

At the moment you can't install a multisite. I've included that ability in the [multisite branch](https://github.com/keesiemeijer/wp-local-version/tree/multisite).

You can use that branch or download the bash file with this (in your /app directory)
```bash
curl -o wp-local-version.sh https://raw.githubusercontent.com/keesiemeijer/wp-local-version/multisite/wp-local-version.sh
```
It adds new variables for installing a [single or multisite install](https://github.com/keesiemeijer/wp-local-version/blob/1a9cb26385fd68eb6a274007d3c83a7533189191/wp-local-version.sh#L106).

It needs some more testing before I will include it in the master branch. Let me know what you think.

**Comment by keesiemeijer** [comment]
I've (merged) added the multisite variables to the master branch. Now you can install multisite for WordPress versions greater than  3.5.1
